// https://nldesignsystem.nl/data-list
export const descriptionListValidationRules = {
  DESCRIPTION_LIST_MUST_CONTAIN_TERM: 'DESCRIPTION_LIST_MUST_CONTAIN_TERM',
  DESCRIPTION_SHOULD_NOT_BE_EMPTY: 'DESCRIPTION_SHOULD_NOT_BE_EMPTY',
  DESCRIPTION_TERM_MUST_HAVE_DESCRIPTION: 'DESCRIPTION_TERM_MUST_HAVE_DESCRIPTION',
  DESCRIPTION_TERM_SHOULD_NOT_BE_EMPTY: 'DESCRIPTION_TERM_SHOULD_NOT_BE_EMPTY',
} as const;
