import '@fontsource/fira-sans/400.css';
import '@fontsource/fira-sans/700.css';
import '@fontsource/source-sans-pro/400.css';
import '@fontsource/source-sans-pro/700.css';
import '@nl-design-system-candidate/button-css/button.css';
import '@utrecht/unordered-list-css/dist/index.css';
import '@nl-design-system-community/ma-design-tokens/dist/theme.css';
import '@utrecht/design-tokens/dist/theme.css';
import './components/alt-text-wizard/index.ts';
