version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        applies-to: "version-updates"
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      nl-design-system:
        applies-to: "version-updates"
        patterns:
          - "@nl-design-system-candidate/*"
          - "@utrecht/*"
      tiptap:
        applies-to: "version-updates"
        patterns:
          - "@tiptap/*"
          - "prosemirror-model"
      storybook:
        applies-to: "version-updates"
        patterns:
          - "@storybook/*"
          - "storybook"
      vite:
        applies-to: "version-updates"
        patterns:
          - "@vitest/*"
          - "vite"
          - "vite-plugin-dts"
          - "vitest"
      astro:
        applies-to: "version-updates"
        patterns:
          - "astro"
          - "@astrojs/*"
      patch-and-minor-dependencies:
        applies-to: "version-updates"
        update-types:
          - "patch"
          - "minor"
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "@types/react"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "@types/react-dom"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "react"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "react-dom"
        update-types:
          - "version-update:semver-major"
    versioning-strategy: "increase-if-necessary"
    open-pull-requests-limit: 20
