// https://nldesignsystem.nl/table
export const tableValidationRules = {
  TABLE_CAPTION_SHOULD_NOT_BE_EMPTY: 'TABLE_CAPTION_SHOULD_NOT_BE_EMPTY',
  TABLE_CELL_SHOULD_NOT_BE_EMPTY: 'TABLE_CELL_SHOULD_NOT_BE_EMPTY',
  TABLE_MUST_HAVE_HEADINGS: 'TABLE_MUST_HAVE_HEADINGS',
  TABLE_MUST_HAVE_MULTIPLE_ROWS: 'TABLE_MUST_HAVE_MULTIPLE_ROWS',
} as const;
