// https://nldesignsystem.nl/heading
export const headingValidationRules = {
  HEADING_LEVEL_MUST_NOT_SKIP: 'HEADING_LEVEL_MUST_NOT_SKIP',
  HEADING_LEVEL_ONE_MUST_BE_UNIQUE: 'HEADING_LEVEL_ONE_MUST_BE_UNIQUE',
  HEADING_MUST_NOT_BE_ABOVE_TOP_LEVEL: 'HEADING_MUST_NOT_BE_ABOVE_TOP_LEVEL',
  HEADING_MUST_NOT_BE_EMPTY: 'HEADING_MUST_NOT_BE_EMPTY',
  HEADING_MUST_START_AT_LEVEL_ONE: 'HEADING_MUST_START_AT_LEVEL_ONE',
  HEADING_SHOULD_NOT_CONTAIN_BOLD_OR_ITALIC: 'HEADING_SHOULD_NOT_CONTAIN_BOLD_OR_ITALIC',
} as const;
