// https://nldesignsystem.nl/paragraph
export const paragraphValidationRules = {
  PARAGRAPH_SHOULD_NOT_BE_EMPTY: 'PARAGRAPH_SHOULD_NOT_BE_EMPTY',
  PARAGRAPH_SHOULD_NOT_BE_ENTIRELY_BOLD: 'PARAGRAPH_SHOULD_NOT_BE_ENTIRELY_BOLD',
  PARAGRAPH_SHOULD_NOT_RESEMBLE_HEADING: 'PARAGRAPH_SHOULD_NOT_RESEMBLE_HEADING',
  PARAGRAPH_SHOULD_NOT_RESEMBLE_LIST: 'PARAGRAPH_SHOULD_NOT_RESEMBLE_LIST',
} as const;
