export const documentValidations = {
  DOCUMENT_MUST_HAVE_CORRECT_HEADING_ORDER: 'DOCUMENT_MUST_HAVE_CORRECT_HEADING_ORDER',
  DOCUMENT_MUST_HAVE_SINGLE_HEADING_ONE: 'DOCUMENT_MUST_HAVE_SINGLE_HEADING_ONE',
  DOCUMENT_MUST_HAVE_TOP_LEVEL_HEADING_ONE: 'DOCUMENT_MUST_HAVE_TOP_LEVEL_HEADING_ONE',
} as const;

export const blockValidations = {
  DEFINITION_DESCRIPTION_MUST_FOLLOW_TERM: 'DEFINITION_DESCRIPTION_MUST_FOLLOW_TERM',
  DESCRIPTION_LIST_MUST_CONTAIN_TERM: 'DESCRIPTION_LIST_MUST_CONTAIN_TERM',
  HEADING_MUST_NOT_BE_EMPTY: 'HEADING_MUST_NOT_BE_EMPTY',
  HEADING_SHOULD_NOT_CONTAIN_BOLD_OR_ITALIC: 'HEADING_SHOULD_NOT_CONTAIN_BOLD_OR_ITALIC',
  IMAGE_MUST_HAVE_ALT_TEXT: 'IMAGE_MUST_HAVE_ALT_TEXT',
  NODE_SHOULD_NOT_BE_EMPTY: 'NODE_SHOULD_NOT_BE_EMPTY',
  PARAGRAPH_SHOULD_NOT_RESEMBLE_HEADING: 'PARAGRAPH_SHOULD_NOT_RESEMBLE_HEADING',
  PARAGRAPH_SHOULD_NOT_RESEMBLE_LIST: 'PARAGRAPH_SHOULD_NOT_RESEMBLE_LIST',
  TABLE_MUST_HAVE_HEADINGS: 'TABLE_MUST_HAVE_HEADINGS',
  TABLE_MUST_HAVE_MULTIPLE_ROWS: 'TABLE_MUST_HAVE_MULTIPLE_ROWS',
} as const;

export const inlineValidations = {
  INLINE_SHOULD_NOT_BE_EMPTY: 'INLINE_SHOULD_NOT_BE_EMPTY',
  INLINE_SHOULD_NOT_BE_UNDERLINED: 'INLINE_SHOULD_NOT_BE_UNDERLINED',
  LINK_SHOULD_NOT_BE_TOO_GENERIC: 'LINK_SHOULD_NOT_BE_TOO_GENERIC',
} as const;

export const validationSeverity = {
  ERROR: 'error',
  INFO: 'info',
  WARNING: 'warning',
} as const;
