export const selectors = {
  BOLD: 'b, strong',
  DESCRIPTION_DETAILS: 'dd',
  DESCRIPTION_LIST: 'dl',
  DESCRIPTION_TERM: 'dt',
  EMPHASIS: 'b, code, del, em, i, mark, s, strike, strong, u',
  HEADING: 'h1, h2, h3, h4, h5, h6',
  HEADING_ONE: 'h1',
  IMAGE: 'img',
  ITALIC: 'em, i',
  LINK: 'a',
  LIST_ITEM: 'li',
  PARAGRAPH: 'p',
  TABLE: 'table',
  TABLE_CAPTION: 'caption',
  TABLE_CELL: 'td, th',
  TABLE_HEADER: 'th',
  TABLE_ROW: 'tr',
  UNDERLINE: 'u',
} as const;
