export const selectors = {
  BOLD: 'b, strong',
  DESCRIPTION_DETAILS: 'dd',
  DESCRIPTION_LIST: 'dl',
  DESCRIPTION_TERM: 'dt',
  HEADING: 'h1, h2, h3, h4, h5, h6',
  HEADING_ONE: 'h1',
  IMAGE: 'img',
  ITALIC: 'em, i',
  LINK: 'a',
  ORDERED_LIST_ITEM: 'ol > li',
  PARAGRAPH: 'p',
  PARAGRAPH_FORMATTING: 'p :is(b, code, del, em, i, mark, s, strike, strong, u)',
  PARAGRAPH_UNDERLINE: 'p u',
  TABLE: 'table',
  TABLE_CAPTION: 'caption',
  TABLE_CELL: 'td, th',
  TABLE_HEADER: 'th',
  TABLE_ROW: 'tr',
  UNORDERED_LIST_ITEM: 'ul > li',
} as const;
