<?php

declare(strict_types=1);

namespace Drupal\clippy\Plugin\CKEditor5Plugin;

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\StringTranslation\StringTranslationTrait;
use Drupal\ckeditor5\Plugin\CKEditor5PluginConfigurableTrait;
use Drupal\ckeditor5\Plugin\CKEditor5PluginDefault;
use Drupal\ckeditor5\Plugin\CKEditor5PluginElementsSubsetInterface;
use Drupal\editor\EditorInterface;

/**
 * Makes the content classes editable per text format.
 *
 * The fields, their labels and their defaults come from content-classes.json,
 * generated by the ckeditor-plugin build.
 */
class ContentClasses extends CKEditor5PluginDefault implements CKEditor5PluginElementsSubsetInterface {

  use CKEditor5PluginConfigurableTrait;
  use StringTranslationTrait;

  /**
   * Tags no Drupal text format can create, so no class may be claimed on them.
   *
   * Drupal rewrites a caption to `data-caption` on `<img>`, so nothing ever creates
   * `<figure>`, and `<h1>` is off in every stock format's Heading plugin. Claiming either
   * fails validation with "needs another plugin to create". This cannot be decided per
   * format: ::getElementsSubset() only receives this plugin's own configuration.
   */
  private const NON_CREATABLE_TAGS = ['figure', 'h1'];

  private static ?array $contentClassesJson = NULL;

  /**
   * {@inheritdoc}
   */
  public function defaultConfiguration(): array {
    return ['classes' => array_column(self::fields(), 'defaultValue', 'key')];
  }

  /**
   * {@inheritdoc}
   */
  public function buildConfigurationForm(array $form, FormStateInterface $form_state): array {
    $classes = $this->classes();
    $form['classes'] = [
      '#type' => 'fieldset',
      '#title' => $this->t('Content classes'),
      '#description' => $this->t('Added to the HTML this editor produces. The defaults match the NL Design System. Leave a field empty to output that element without a class.'),
      '#tree' => TRUE,
    ];

    foreach (self::fields() as $key => $field) {
      $form['classes'][$key] = [
        '#type' => 'textfield',
        '#title' => $this->t($field['label']),
        '#default_value' => $classes[$key],
        '#size' => 60,
        '#description' => self::hasToken($field['defaultValue'])
          ? $this->t('@token is replaced by the level of the heading, 1 through 6.', ['@token' => self::token()])
          : NULL,
      ];
    }

    return $form;
  }

  /**
   * {@inheritdoc}
   */
  public function validateConfigurationForm(array &$form, FormStateInterface $form_state): void {
    foreach (array_keys(self::fields()) as $key) {
      // Anything that would need escaping inside class="…" cannot be part of a class name.
      if (preg_match('/[\'"<>&]/', (string) $form_state->getValue(['classes', $key], '')) === 1) {
        $form_state->setError($form['classes'][$key], $this->t('This is not a valid class name.'));
      }
    }
  }

  /**
   * {@inheritdoc}
   */
  public function submitConfigurationForm(array &$form, FormStateInterface $form_state): void {
    foreach (array_keys(self::fields()) as $key) {
      $value = (string) $form_state->getValue(['classes', $key], '');
      // Single-spaced, so the stored value matches what the editor emits.
      $this->configuration['classes'][$key] = (string) preg_replace('/\s+/', ' ', trim($value));
    }
  }

  /**
   * {@inheritdoc}
   */
  public function getDynamicPluginConfig(array $static_plugin_config, EditorInterface $editor): array {
    return $static_plugin_config + ['contentClasses' => $this->classes()];
  }

  /**
   * {@inheritdoc}
   *
   * Narrows the `<tag class>` superset in clippy.ckeditor5.yml to the configured values.
   */
  public function getElementsSubset(): array {
    $subset = [];
    foreach ($this->classes() as $key => $value) {
      foreach (array_diff(self::fields()[$key]['tags'] ?? [], self::NON_CREATABLE_TAGS) as $tag) {
        $resolved = self::resolve($value, $tag);
        if ($resolved !== '') {
          $subset[] = sprintf('<%s class="%s">', $tag, $resolved);
        }
      }
    }
    return $subset;
  }

  /**
   * The configured classes, plus the default of any field with no stored value yet.
   */
  private function classes(): array {
    return ($this->configuration['classes'] ?? []) + $this->defaultConfiguration()['classes'];
  }

  /**
   * Fills in the heading level token, mirroring the JavaScript plugin: the level comes from
   * the rendered tag, because CKEditor renders `heading1` as `<h2>` by default.
   */
  private static function resolve(string $value, string $tag): string {
    $value = trim($value);
    if (!self::hasToken($value)) {
      return $value;
    }
    // A pattern without a level to fill in would render as `nl-heading--level-`.
    return preg_match('/^h([1-6])$/', $tag, $matches) === 1 ? str_replace(self::token(), $matches[1], $value) : '';
  }

  private static function hasToken(string $value): bool {
    return self::token() !== '' && str_contains($value, self::token());
  }

  private static function token(): string {
    return self::contentClassesJson()['headingLevelToken'] ?? '';
  }

  private static function fields(): array {
    return array_column(self::contentClassesJson()['fields'] ?? [], NULL, 'key');
  }

  /**
   * Reads content-classes.json.
   *
   * Located relative to this file rather than through the module list because Drupal
   * validates a plugin's default configuration on an instance built with
   * \ReflectionClass::newInstanceWithoutConstructor(): no constructor runs, so nothing can
   * be injected.
   *
   * @see \Drupal\ckeditor5\Plugin\CKEditor5PluginDefinition::validateDrupalAspects()
   */
  private static function contentClassesJson(): array {
    if (self::$contentClassesJson === NULL) {
      $path = dirname(__DIR__, 3) . '/content-classes.json';
      $decoded = is_readable($path) ? json_decode((string) file_get_contents($path), TRUE) : NULL;
      self::$contentClassesJson = is_array($decoded) ? $decoded : [];
    }
    return self::$contentClassesJson;
  }

}
