export const ITEM = {
  ACCESSIBILITY_NOTIFICATIONS: 'accessibility-notifications',
  BOLD: 'bold',
  BULLET_LIST: 'bullet-list',
  CODE: 'code',
  DEFINITION_LIST: 'definition-list',
  FORMAT_SELECT: 'format-select',
  HIGHLIGHT: 'highlight',
  HORIZONTAL_RULE: 'horizontal-rule',
  IMAGE_UPLOAD: 'image-upload',
  INSERT_TABLE: 'insert-table',
  ITALIC: 'italic',
  KEYBOARD_SHORTCUTS: 'keyboard-shortcuts',
  LANGUAGE_SELECT: 'language-select',
  LINK: 'link',
  ORDERED_LIST: 'ordered-list',
  REDO: 'redo',
  STRIKE: 'strike',
  SUBSCRIPT: 'subscript',
  SUPERSCRIPT: 'superscript',
  TEXT_ALIGN: 'text-align',
  TEXT_DIRECTION_LTR: 'text-direction-ltr',
  TEXT_DIRECTION_RTL: 'text-direction-rtl',
  UNDERLINE: 'underline',
  UNDO: 'undo',
} as const;

export const GROUP = {
  ALIGNMENT: 'alignment',
  HISTORY: 'history',
  INSERT: 'insert',
  LISTS: 'lists',
  SELECTS: 'selects',
  TABLE: 'table',
  TEXT_DIRECTION: 'text-direction',
  TEXT_STYLING: 'text-styling',
  TOOLS: 'tools',
} as const;
