import { TOOLBAR_ITEM } from './constants.ts';

export type ToolbarItem = (typeof TOOLBAR_ITEM)[keyof typeof TOOLBAR_ITEM];

export type ToolbarConfig = ToolbarItem[][];

export const defaultToolbarConfig: ToolbarConfig = [
  [TOOLBAR_ITEM.FORMAT_SELECT, TOOLBAR_ITEM.LANGUAGE_SELECT],
  [
    TOOLBAR_ITEM.BOLD,
    TOOLBAR_ITEM.ITALIC,
    TOOLBAR_ITEM.UNDERLINE,
    TOOLBAR_ITEM.STRIKE,
    TOOLBAR_ITEM.CODE,
    TOOLBAR_ITEM.HIGHLIGHT,
    TOOLBAR_ITEM.SUPERSCRIPT,
    TOOLBAR_ITEM.SUBSCRIPT,
  ],
  [TOOLBAR_ITEM.UNDO, TOOLBAR_ITEM.REDO],
  [TOOLBAR_ITEM.ORDERED_LIST, TOOLBAR_ITEM.BULLET_LIST, TOOLBAR_ITEM.DEFINITION_LIST],
  [TOOLBAR_ITEM.INSERT_TABLE],
  [TOOLBAR_ITEM.TEXT_ALIGN],
  [TOOLBAR_ITEM.LINK, TOOLBAR_ITEM.IMAGE_UPLOAD, TOOLBAR_ITEM.HORIZONTAL_RULE],
  [TOOLBAR_ITEM.TEXT_DIRECTION_LTR, TOOLBAR_ITEM.TEXT_DIRECTION_RTL],
  [TOOLBAR_ITEM.KEYBOARD_SHORTCUTS, TOOLBAR_ITEM.ACCESSIBILITY_NOTIFICATIONS],
];
