export const CustomEvents = {
  FOCUS_NODE: 'FOCUS_NODE',
  FOCUS_TOOLBAR: 'FOCUS_TOOLBAR',
  OPEN_VALIDATIONS_DIALOG: 'OPEN_VALIDATIONS_DIALOG',
  TEXT_FORMAT_CHANGE: 'TEXT_FORMAT_CHANGE',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
} as const;
