export const CustomEvents = {
  CORRECT_VALIDATION_ISSUE: 'CORRECT_VALIDATION_ISSUE',
  FOCUS_BUBBLE_MENU: 'FOCUS_BUBBLE_MENU',
  FOCUS_NODE: 'FOCUS_NODE',
  FOCUS_TOOLBAR: 'FOCUS_TOOLBAR',
  FOCUS_VALIDATION_ITEM_IN_DRAWER: 'FOCUS_VALIDATION_ITEM_IN_DRAWER',
  FOCUS_VALIDATION_ITEM_IN_GUTTER: 'FOCUS_VALIDATION_ITEM_IN_GUTTER',
  FOCUS_VALIDATION_ITEM_IN_LIST: 'FOCUS_VALIDATION_ITEM_IN_LIST',
  OPEN_DOCUMENT_OVERVIEW: 'OPEN_DOCUMENT_OVERVIEW',
  OPEN_IMAGE_DIALOG: 'OPEN_IMAGE_DIALOG',
  OPEN_VALIDATIONS_DIALOG: 'OPEN_VALIDATIONS_DIALOG',
  TAB_CHANGE: 'TAB_CHANGE',
  TEXT_FORMAT_CHANGE: 'TEXT_FORMAT_CHANGE',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
} as const;

export type DocumentOverviewMode = 'heading-structure' | 'link-list';

export interface OpenDocumentOverviewDetail {
  mode: DocumentOverviewMode;
}

